// Bake short-range ambient occlusion into direct-mesh vertex alpha.
#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <numeric>
#include <stdexcept>
#include <string>
#include <vector>
struct V {float x,y,z;V operator+(V b)const{return{x+b.x,y+b.y,z+b.z};}V operator-(V b)const{return{x-b.x,y-b.y,z-b.z};}V operator*(float s)const{return{x*s,y*s,z*s};}};
float dot(V a,V b){return a.x*b.x+a.y*b.y+a.z*b.z;}V cross(V a,V b){return{a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x};}V norm(V v){float l=std::sqrt(dot(v,v));return l>.00001f?v*(1/l):V{0,0,1};}float axis(V v,int i){return i==0?v.x:i==1?v.y:v.z;}
struct Vertex {V p,n;float uv[2],color[4];};static_assert(sizeof(Vertex)==48);
struct Batch {std::string texture;std::vector<Vertex> vertices;};struct Tri{V a,b,c,lo,hi,center;};struct Node{V lo,hi;int begin,end,left=-1,right=-1;};
V low(V a,V b){return{std::min(a.x,b.x),std::min(a.y,b.y),std::min(a.z,b.z)};}V high(V a,V b){return{std::max(a.x,b.x),std::max(a.y,b.y),std::max(a.z,b.z)};}
struct Tree {
 std::vector<Tri> tris;std::vector<int> order;std::vector<Node> nodes;
 int build(int b,int e){Node n{tris[order[b]].lo,tris[order[b]].hi,b,e};for(int i=b+1;i<e;++i){n.lo=low(n.lo,tris[order[i]].lo);n.hi=high(n.hi,tris[order[i]].hi);}int id=nodes.size();nodes.push_back(n);if(e-b>8){auto size=n.hi-n.lo;int dim=size.x>size.y?0:1;if(size.z>axis(size,dim))dim=2;int mid=(b+e)/2;std::nth_element(order.begin()+b,order.begin()+mid,order.begin()+e,[&](int a,int c){return axis(tris[a].center,dim)<axis(tris[c].center,dim);});int left=build(b,mid),right=build(mid,e);nodes[id].left=left;nodes[id].right=right;}return id;}
 bool box(const Node& n,V o,V d,float range)const{float near=0,far=range;for(int i=0;i<3;++i){float direction=axis(d,i),origin=axis(o,i),lo=axis(n.lo,i),hi=axis(n.hi,i);if(std::abs(direction)<1e-8f){if(origin<lo||origin>hi)return false;continue;}float a=(lo-origin)/direction,b=(hi-origin)/direction;if(a>b)std::swap(a,b);near=std::max(near,a);far=std::min(far,b);if(near>far)return false;}return true;}
 bool hit(int id,V o,V d,float range)const{const auto& n=nodes[id];if(!box(n,o,d,range))return false;if(n.left>=0)return hit(n.left,o,d,range)||hit(n.right,o,d,range);for(int i=n.begin;i<n.end;++i){const auto& t=tris[order[i]];auto e1=t.b-t.a,e2=t.c-t.a,p=cross(d,e2);float det=dot(e1,p);if(std::abs(det)<1e-8f)continue;float inv=1/det;auto delta=o-t.a;float u=dot(delta,p)*inv;if(u<0||u>1)continue;auto q=cross(delta,e1);float v=dot(d,q)*inv;if(v<0||u+v>1)continue;float distance=dot(e2,q)*inv;if(distance>.02f&&distance<range)return true;}return false;}
};
template<class T>T read(std::istream& f){T v{};f.read(reinterpret_cast<char*>(&v),sizeof v);if(!f)throw std::runtime_error("Truncated mesh");return v;}template<class T>void write(std::ostream& f,T v){f.write(reinterpret_cast<const char*>(&v),sizeof v);}
int main(int argc,char** argv){try{if(argc!=3)throw std::runtime_error("usage: bake_mesh_ao input.rmesh output.rmesh");std::ifstream in(argv[1],std::ios::binary);if(read<std::uint32_t>(in)!=0x314d4252)throw std::runtime_error("Wrong mesh format");auto count=read<std::uint32_t>(in);if(!count||count>32)throw std::runtime_error("Invalid batches");std::vector<Batch> batches;Tree tree;for(unsigned i=0;i<count;++i){auto len=read<std::uint32_t>(in);if(len>256)throw std::runtime_error("Invalid path");Batch b;b.texture.resize(len);in.read(b.texture.data(),len);auto n=read<std::uint32_t>(in);if(!n||n>500000||n%3)throw std::runtime_error("Invalid vertices");b.vertices.resize(n);in.read(reinterpret_cast<char*>(b.vertices.data()),n*sizeof(Vertex));if(!in)throw std::runtime_error("Truncated vertices");for(unsigned v=0;v<n;v+=3){auto a=b.vertices[v].p,c=b.vertices[v+1].p,d=b.vertices[v+2].p;tree.tris.push_back({a,c,d,low(a,low(c,d)),high(a,high(c,d)),(a+c+d)*(1/3.f)});}batches.push_back(std::move(b));}tree.order.resize(tree.tris.size());std::iota(tree.order.begin(),tree.order.end(),0);tree.build(0,tree.order.size());float minimum=1,mean=0;std::size_t total=0;for(auto& b:batches)for(auto& v:b.vertices){auto n=norm(v.n),t=norm(cross(n,std::abs(n.z)<.9f?V{0,0,1}:V{0,1,0})),bitangent=cross(n,t);int occluded=0;constexpr int samples=12;for(int ray=0;ray<samples;++ray){float r=std::sqrt((ray+.5f)/samples),angle=ray*2.39996323f;auto direction=t*(r*std::cos(angle))+bitangent*(r*std::sin(angle))+n*std::sqrt(1-r*r);if(tree.hit(0,v.p+n*.3f,direction,24.f))++occluded;}float ao=1-.7f*occluded/samples;v.color[3]=ao;minimum=std::min(minimum,ao);mean+=ao;++total;}std::ofstream out(argv[2],std::ios::binary);write(out,std::uint32_t{0x314d4252});write(out,count);for(const auto& b:batches){write(out,static_cast<std::uint32_t>(b.texture.size()));out.write(b.texture.data(),b.texture.size());write(out,static_cast<std::uint32_t>(b.vertices.size()));out.write(reinterpret_cast<const char*>(b.vertices.data()),b.vertices.size()*sizeof(Vertex));}if(!out)throw std::runtime_error("Write failed");std::cout<<total<<" vertices, AO min "<<minimum<<" mean "<<mean/total<<'\n';}catch(const std::exception& e){std::cerr<<e.what()<<'\n';return 1;}}
